import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import {
  CHAKCHAK_FEATURES,
  CHAKCHAK_TRAINING_ENVELOPE,
  buildChakchakFeatureVector
} from "../src/chakchak-features.js";
import { predictMonotonicQuantileGbdt } from "../src/monotonic-gbdt.js";
import {
  DATASET_VERSION,
  TEACHER_SIMULATIONS_PER_ROW,
  TRAINING_SEGMENTS,
  VALIDATION_SEGMENTS,
  generateChakchakSimulationDataset
} from "./lib/chakchak-simulation-dataset.mjs";
import {
  fitMonotonicQuantileGbdt,
  quantile,
  summarizeQuantilePredictions
} from "./lib/monotonic-quantile-gbdt.mjs";

const TRAINED_AT = "2026-08-06T00:00:00.000Z";
const OUTPUT_FILE = resolve("src/chakchak-model-data.js");
const DATASET_OUTPUT = resolve("output/model/chakchak-simulation-v3.json");

const dataset = generateChakchakSimulationDataset();
const constrainedFeatures = Object.freeze({
  flightDelayMinutes: 1,
  weatherSeverity: 1,
  immigrationSeverity: 1,
  baggageDelayMinutes: 1,
  checkedBaggage: 1,
  accessibilityNeeds: 1,
  largeLuggage: 1,
  terminalT2: 1,
  timePeakSeverity: 1
});
const timeFeatureIds = Object.freeze([
  ...Object.keys(constrainedFeatures),
  "arrivalHourSin",
  "arrivalHourCos"
]);
const commonOptions = {
  featureIds: timeFeatureIds,
  constraints: constrainedFeatures,
  baselineFeature: "expectedProcessMinutes",
  estimators: 88,
  learningRate: 0.06,
  thresholdCandidates: 16,
  minimumLeafRows: 44
};

const heads = {
  p50Minutes: fitMonotonicQuantileGbdt(dataset.trainingRows, { ...commonOptions, quantile: 0.5 }),
  p90Minutes: fitMonotonicQuantileGbdt(dataset.trainingRows, { ...commonOptions, quantile: 0.9 }),
  p95Minutes: fitMonotonicQuantileGbdt(dataset.trainingRows, { ...commonOptions, quantile: 0.95 })
};
heads.p90Minutes.safetyCalibrationQuantile = 0.9;
heads.p95Minutes.safetyCalibrationQuantile = 0.95;
heads.p90Minutes.safetyOffsetMinutes = calibrateCoverageOffset(dataset.calibrationRows, heads.p90Minutes, 0.9);
heads.p95Minutes.safetyOffsetMinutes = calibrateCoverageOffset(dataset.calibrationRows, heads.p95Minutes, 0.95);
heads.boardingProbability = fitProbabilityHead(dataset.trainingRows, heads.p90Minutes);

const metrics = evaluateModel(dataset.validationRows, heads);
const segmentMetrics = Object.fromEntries(
  Object.entries(dataset.validationBySegment).map(([segment, rows]) => [segment, evaluateModel(rows, heads)])
);
const monotonicAudit = evaluateMonotonicity(heads);
assertQuality(metrics, segmentMetrics, monotonicAudit);

const artifact = {
  schemaVersion: "2.0",
  id: "chakchak-connection-ai",
  name: "착착 Connection AI",
  version: "2.0.0-sim",
  modelType: "monotonic quantile gradient boosted decision trees + monotonic probability calibration",
  trainedAt: TRAINED_AT,
  datasetVersion: DATASET_VERSION,
  training: {
    source: "착착 Monte Carlo 엔진이 생성한 터미널·시간대 층화 시뮬레이션 데이터",
    labelDefinition: "각 여행 상황의 독립 관측 1건으로 분위수 손실을 학습하고 1,200회 참고 분포로 별도 비교",
    trainingRows: dataset.trainingRows.length,
    calibrationRows: dataset.calibrationRows.length,
    validationRows: dataset.validationRows.length,
    teacherSimulationsPerRow: TEACHER_SIMULATIONS_PER_ROW,
    trainingSegments: TRAINING_SEGMENTS,
    validationSegments: VALIDATION_SEGMENTS,
    realWorldCalibrated: false,
    inputEnvelope: CHAKCHAK_TRAINING_ENVELOPE
  },
  features: CHAKCHAK_FEATURES,
  bounds: {
    p50Minutes: [15, 600],
    p90Minutes: [20, 720],
    p95Minutes: [20, 780],
    boardingProbability: [0.001, 0.999]
  },
  metrics: {
    ...metrics,
    segments: segmentMetrics,
    monotonicAudit
  },
  heads,
  disclaimer: "터미널·시간대를 포함한 층화 시뮬레이션으로 학습·검증한 모델이며 실제 승객 운영 성능이 아닙니다."
};

const source = `// Generated by scripts/train_chakchak_model.mjs. Do not edit weights by hand.\nexport const chakchakConnectionModel = Object.freeze(${JSON.stringify(artifact)});\n`;
await mkdir(dirname(DATASET_OUTPUT), { recursive: true });
await writeFile(OUTPUT_FILE, source, "utf8");
await writeFile(DATASET_OUTPUT, `${JSON.stringify({
  version: dataset.version,
  methodology: "SIMULATED_OBSERVATION_AND_MONTE_CARLO_REFERENCE",
  teacherSimulationsPerRow: TEACHER_SIMULATIONS_PER_ROW,
  trainingRows: dataset.trainingRows,
  calibrationRows: dataset.calibrationRows,
  validationBySegment: dataset.validationBySegment
})}\n`, "utf8");
console.log(`착착 Connection AI ${artifact.version} 학습 완료`);
console.log(JSON.stringify({ metrics, segmentMetrics, monotonicAudit, trees: treeCounts(heads) }, null, 2));
console.log(`모델 저장: ${OUTPUT_FILE}`);
console.log(`고정 데이터 저장: ${DATASET_OUTPUT}`);

function calibrateCoverageOffset(rows, head, coverageTarget) {
  const errors = rows.map((row) => row.observedMinutes - predictMonotonicQuantileGbdt(head, row.features));
  return round(Math.max(0, quantile(errors, coverageTarget)), 3);
}

function fitProbabilityHead(rows, p90Head) {
  const points = rows.map((row) => ({
    x: row.features.connectionWindowMinutes - row.features.boardingBufferMinutes - predictMonotonicQuantileGbdt(p90Head, row.features),
    y: row.teacher.boardingProbability
  }));
  return {
    type: "monotonic-isotonic-v3",
    feature: "gbdtP90MarginMinutes",
    knots: fitIsotonicKnots(points),
    constraints: {
      connectionWindowMinutes: "increasing",
      flightDelayMinutes: "decreasing",
      weatherSeverity: "decreasing",
      immigrationSeverity: "decreasing",
      baggageDelayMinutes: "decreasing",
      checkedBaggage: "decreasing",
      accessibilityNeeds: "decreasing",
      largeLuggage: "decreasing",
      terminalT2: "decreasing",
      timePeakSeverity: "decreasing"
    }
  };
}

function evaluateModel(rows, modelHeads) {
  const values = rows.map((row) => {
    const rawP50 = predictMonotonicQuantileGbdt(modelHeads.p50Minutes, row.features);
    const rawP90 = predictMonotonicQuantileGbdt(modelHeads.p90Minutes, row.features);
    const rawP95 = predictMonotonicQuantileGbdt(modelHeads.p95Minutes, row.features);
    const p50 = rawP50;
    const p90 = Math.max(p50, rawP90);
    const p95 = Math.max(p90, rawP95);
    const margin = row.features.connectionWindowMinutes - row.features.boardingBufferMinutes - p90;
    const probability = clamp(interpolateKnots(modelHeads.boardingProbability.knots, margin), 0.001, 0.999);
    return { row, p50, p90, p95, probability, rawP50, rawP90, rawP95 };
  });
  const p50 = summarizeQuantilePredictions(values.map(({ row, p50: predicted }) => ({ observed: row.observedMinutes, reference: row.teacher.p50, predicted })), 0.5);
  const p90 = summarizeQuantilePredictions(values.map(({ row, p90: predicted }) => ({ observed: row.observedMinutes, reference: row.teacher.p90, predicted })), 0.9);
  const p95 = summarizeQuantilePredictions(values.map(({ row, p95: predicted }) => ({ observed: row.observedMinutes, reference: row.teacher.p95, predicted })), 0.95);
  const probabilityPairs = values.map(({ row, probability }) => [row.teacher.boardingProbability, probability]);
  const p90ReferenceErrors = values.map(({ row, p90: predicted }) => predicted - row.teacher.p90);
  return {
    p50MaeMinutes: p50.referenceMaeMinutes,
    p90MaeMinutes: p90.referenceMaeMinutes,
    p95MaeMinutes: p95.referenceMaeMinutes,
    p90UnderpredictionRate: round(p90ReferenceErrors.filter((error) => error < 0).length / rows.length, 4),
    p90MeanSafetyBiasMinutes: round(mean(p90ReferenceErrors), 3),
    quantiles: { p50, p90, p95 },
    probabilityMae: round(mean(probabilityPairs.map(([actual, predicted]) => Math.abs(actual - predicted))), 4),
    simulatorProbabilityMse: round(mean(probabilityPairs.map(([actual, predicted]) => (actual - predicted) ** 2)), 4),
    simulatorCalibrationError: round(expectedCalibrationError(probabilityPairs), 4),
    crossingRateBeforeOrdering: round(values.filter((item) => item.rawP50 > item.rawP90 || item.rawP90 > item.rawP95).length / rows.length, 4),
    validationRows: rows.length
  };
}

function evaluateMonotonicity(modelHeads) {
  const random = mulberry32(0x20260824);
  let violations = 0;
  let comparisons = 0;
  for (let index = 0; index < 300; index += 1) {
    const input = sampleAuditInput(random);
    const current = predictAll(input, modelHeads);
    for (const [feature, increment] of [["flightDelayMinutes", 10], ["weatherSeverity", 0.2], ["immigrationSeverity", 0.2], ["baggageDelayMinutes", 5]]) {
      const increased = predictAll({ ...input, [feature]: input[feature] + increment }, modelHeads);
      for (const quantileId of ["p50", "p90", "p95"]) {
        violations += Number(increased[quantileId] + 1e-9 < current[quantileId]);
        comparisons += 1;
      }
      violations += Number(increased.probability - 1e-9 > current.probability);
      comparisons += 1;
    }
    const later = predictAll({ ...input, connectionWindowMinutes: input.connectionWindowMinutes + 20 }, modelHeads);
    violations += Number(later.probability + 1e-9 < current.probability);
    comparisons += 1;
  }
  return { comparisons, violations, violationRate: round(violations / comparisons, 6) };
}

function predictAll(input, modelHeads) {
  const features = buildChakchakFeatureVector(input);
  const p50 = predictMonotonicQuantileGbdt(modelHeads.p50Minutes, features);
  const p90 = Math.max(p50, predictMonotonicQuantileGbdt(modelHeads.p90Minutes, features));
  const p95 = Math.max(p90, predictMonotonicQuantileGbdt(modelHeads.p95Minutes, features));
  const margin = features.connectionWindowMinutes - features.boardingBufferMinutes - p90;
  const probability = interpolateKnots(modelHeads.boardingProbability.knots, margin);
  return { p50, p90, p95, probability };
}

function sampleAuditInput(random) {
  const checkedBaggage = random() < 0.72;
  return {
    flightDelayMinutes: random() * 190,
    weatherSeverity: random() * 1.8,
    immigrationSeverity: random() * 1.8,
    baggageDelayMinutes: checkedBaggage ? random() * 50 : 0,
    checkedBaggage,
    accessibilityNeeds: random() < 0.2,
    largeLuggage: random() < 0.3,
    terminal: random() < 0.55 ? "T2" : "T1",
    arrivalHourLocal: random() * 23.9,
    connectionWindowMinutes: 70 + random() * 240,
    boardingBufferMinutes: 3 + random() * 12
  };
}

function assertQuality(modelMetrics, segments, monotonic) {
  const failures = [];
  if (modelMetrics.quantiles.p50.referenceMaeMinutes > 6) failures.push(`P50 참고분포 MAE ${modelMetrics.quantiles.p50.referenceMaeMinutes}`);
  if (modelMetrics.quantiles.p90.referenceMaeMinutes > 9) failures.push(`P90 참고분포 MAE ${modelMetrics.quantiles.p90.referenceMaeMinutes}`);
  if (modelMetrics.quantiles.p95.referenceMaeMinutes > 11) failures.push(`P95 참고분포 MAE ${modelMetrics.quantiles.p95.referenceMaeMinutes}`);
  if (modelMetrics.quantiles.p90.coverage < 0.84) failures.push(`P90 포함률 ${modelMetrics.quantiles.p90.coverage}`);
  if (modelMetrics.quantiles.p95.coverage < 0.9) failures.push(`P95 포함률 ${modelMetrics.quantiles.p95.coverage}`);
  if (segments.stress.quantiles.p90.referenceMaeMinutes > 12) failures.push(`스트레스 P90 MAE ${segments.stress.quantiles.p90.referenceMaeMinutes}`);
  if (modelMetrics.probabilityMae > 0.08) failures.push(`확률 MAE ${modelMetrics.probabilityMae}`);
  if (monotonic.violations > 0) failures.push(`단조성 위반 ${monotonic.violations}`);
  if (failures.length) throw new Error(`착착 v2 품질 기준 미달: ${failures.join(", ")}`);
}

function fitIsotonicKnots(points) {
  const sorted = [...points].sort((left, right) => left.x - right.x);
  const blocks = [];
  for (const point of sorted) {
    blocks.push({ sumX: point.x, sumY: point.y, count: 1, value: point.y });
    while (blocks.length > 1 && blocks.at(-2).value >= blocks.at(-1).value) {
      const right = blocks.pop();
      const left = blocks.pop();
      const merged = { sumX: left.sumX + right.sumX, sumY: left.sumY + right.sumY, count: left.count + right.count };
      merged.value = merged.sumY / merged.count;
      blocks.push(merged);
    }
  }
  return blocks.map((block) => ({ x: round(block.sumX / block.count, 6), value: round(block.value, 8), samples: block.count }));
}

function interpolateKnots(knots, value) {
  if (value <= knots[0].x) return knots[0].value;
  if (value >= knots.at(-1).x) return knots.at(-1).value;
  let low = 0;
  let high = knots.length - 1;
  while (low + 1 < high) {
    const middle = Math.floor((low + high) / 2);
    if (knots[middle].x <= value) low = middle;
    else high = middle;
  }
  const left = knots[low];
  const right = knots[high];
  const ratio = (value - left.x) / Math.max(1e-9, right.x - left.x);
  return left.value + ratio * (right.value - left.value);
}

function expectedCalibrationError(pairs) {
  let weighted = 0;
  for (let bin = 0; bin < 10; bin += 1) {
    const lower = bin / 10;
    const upper = (bin + 1) / 10;
    const items = pairs.filter(([, prediction]) => prediction >= lower && (bin === 9 ? prediction <= upper : prediction < upper));
    if (!items.length) continue;
    weighted += items.length / pairs.length * Math.abs(mean(items.map(([actual]) => actual)) - mean(items.map(([, prediction]) => prediction)));
  }
  return weighted;
}

function treeCounts(modelHeads) {
  return Object.fromEntries(Object.entries(modelHeads).map(([id, head]) => [id, head.trees?.length || 0]));
}

function mulberry32(seed) {
  let state = seed >>> 0;
  return () => {
    state += 0x6d2b79f5;
    let value = state;
    value = Math.imul(value ^ value >>> 15, value | 1);
    value ^= value + Math.imul(value ^ value >>> 7, value | 61);
    return ((value ^ value >>> 14) >>> 0) / 4_294_967_296;
  };
}

function mean(values) {
  return values.reduce((sum, value) => sum + value, 0) / values.length;
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function round(value, digits) {
  const scale = 10 ** digits;
  return Math.round(value * scale) / scale;
}
